version: '3.8'

services:

  postgis:
    image: pgrouting/pgrouting:latest
    environment:
      POSTGRES_DB: o2p
      POSTGRES_USER: o2p
      POSTGRES_PASSWORD: o2p
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  osm2pgrouting:
    image: osm2pgrouting:{{ version }}

volumes:
  postgis_data: